/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "quiz.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

quiz_master *
quizproc_1(quizzer *argp, CLIENT *clnt)
{
	static quiz_master clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUIZPROC,
		(xdrproc_t) xdr_quizzer, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_master, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

quiz_master *
quizscoreproc_1(quizzer *argp, CLIENT *clnt)
{
	static quiz_master clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUIZSCOREPROC,
		(xdrproc_t) xdr_quizzer, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_master, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
