/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _QUIZ_H_RPCGEN
#define _QUIZ_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct quizzer {
	char answer[256];
	char leaderboard[1024];
	char username[256];
	int type;
	u_long userID;
	int x_1;
	int x_2;
};
typedef struct quizzer quizzer;

struct quiz_master {
	char question[1024];
	char leader_board[1024];
	int score_1;
	int question_number;
	int x_1;
	int x_2;
};
typedef struct quiz_master quiz_master;

#define QUIZ_PROG 0x13451111
#define QUIZ_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUIZPROC 1
extern  quiz_master * quizproc_1(quizzer *, CLIENT *);
extern  quiz_master * quizproc_1_svc(quizzer *, struct svc_req *);
extern int quiz_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUIZPROC 1
extern  quiz_master * quizproc_1();
extern  quiz_master * quizproc_1_svc();
extern int quiz_prog_1_freeresult ();
#endif /* K&R C */

#define QUIZSCORE_PROG 0x20000099
#define QUIZSCORE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define QUIZSCOREPROC 1
extern  quiz_master * quizscoreproc_1(quizzer *, CLIENT *);
extern  quiz_master * quizscoreproc_1_svc(quizzer *, struct svc_req *);
extern int quizscore_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define QUIZSCOREPROC 1
extern  quiz_master * quizscoreproc_1();
extern  quiz_master * quizscoreproc_1_svc();
extern int quizscore_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_quizzer (XDR *, quizzer*);
extern  bool_t xdr_quiz_master (XDR *, quiz_master*);

#else /* K&R C */
extern bool_t xdr_quizzer ();
extern bool_t xdr_quiz_master ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_QUIZ_H_RPCGEN */
