/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "quiz.h"

bool_t
xdr_quizzer (XDR *xdrs, quizzer *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->answer, 256,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->leaderboard, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->username, 256,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->userID))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_2))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->type);
			IXDR_PUT_U_LONG(buf, objp->userID);
			IXDR_PUT_LONG(buf, objp->x_1);
			IXDR_PUT_LONG(buf, objp->x_2);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->answer, 256,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->leaderboard, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->username, 256,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->type))
				 return FALSE;
			 if (!xdr_u_long (xdrs, &objp->userID))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_2))
				 return FALSE;
		} else {
			objp->type = IXDR_GET_LONG(buf);
			objp->userID = IXDR_GET_U_LONG(buf);
			objp->x_1 = IXDR_GET_LONG(buf);
			objp->x_2 = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->answer, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->leaderboard, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->username, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->userID))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x_2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_quiz_master (XDR *xdrs, quiz_master *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->question, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->leader_board, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->score_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->question_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_2))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->score_1);
			IXDR_PUT_LONG(buf, objp->question_number);
			IXDR_PUT_LONG(buf, objp->x_1);
			IXDR_PUT_LONG(buf, objp->x_2);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->question, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->leader_board, 1024,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->score_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->question_number))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_1))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->x_2))
				 return FALSE;
		} else {
			objp->score_1 = IXDR_GET_LONG(buf);
			objp->question_number = IXDR_GET_LONG(buf);
			objp->x_1 = IXDR_GET_LONG(buf);
			objp->x_2 = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->question, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->leader_board, 1024,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->score_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->question_number))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->x_2))
		 return FALSE;
	return TRUE;
}
